// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/platform/proto/runtimesample/runtimesample.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_kernel_platform_runtimesample is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/platform/proto/runtimesample/runtimesample.proto

It has these top-level messages:
	RuntimeSample
*/
package com_HailoOSS_kernel_platform_runtimesample

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type RuntimeSample struct {
	ServiceName      *string `protobuf:"bytes,1,req,name=serviceName" json:"serviceName,omitempty"`
	InstanceId       *string `protobuf:"bytes,2,req,name=instanceId" json:"instanceId,omitempty"`
	Timestamp        *int64  `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	HeapInUse        *uint64 `protobuf:"varint,4,req,name=heapInUse" json:"heapInUse,omitempty"`
	HeapTotal        *uint64 `protobuf:"varint,5,req,name=heapTotal" json:"heapTotal,omitempty"`
	HeapReleased     *uint64 `protobuf:"varint,6,req,name=heapReleased" json:"heapReleased,omitempty"`
	LastGCDuration   *uint64 `protobuf:"varint,7,req,name=lastGCDuration" json:"lastGCDuration,omitempty"`
	NumGC            *uint32 `protobuf:"varint,8,req,name=numGC" json:"numGC,omitempty"`
	NumGoRoutines    *uint32 `protobuf:"varint,9,req,name=numGoRoutines" json:"numGoRoutines,omitempty"`
	Uptime           *int64  `protobuf:"varint,10,req,name=uptime" json:"uptime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RuntimeSample) Reset()         { *m = RuntimeSample{} }
func (m *RuntimeSample) String() string { return proto.CompactTextString(m) }
func (*RuntimeSample) ProtoMessage()    {}

func (m *RuntimeSample) GetServiceName() string {
	if m != nil && m.ServiceName != nil {
		return *m.ServiceName
	}
	return ""
}

func (m *RuntimeSample) GetInstanceId() string {
	if m != nil && m.InstanceId != nil {
		return *m.InstanceId
	}
	return ""
}

func (m *RuntimeSample) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *RuntimeSample) GetHeapInUse() uint64 {
	if m != nil && m.HeapInUse != nil {
		return *m.HeapInUse
	}
	return 0
}

func (m *RuntimeSample) GetHeapTotal() uint64 {
	if m != nil && m.HeapTotal != nil {
		return *m.HeapTotal
	}
	return 0
}

func (m *RuntimeSample) GetHeapReleased() uint64 {
	if m != nil && m.HeapReleased != nil {
		return *m.HeapReleased
	}
	return 0
}

func (m *RuntimeSample) GetLastGCDuration() uint64 {
	if m != nil && m.LastGCDuration != nil {
		return *m.LastGCDuration
	}
	return 0
}

func (m *RuntimeSample) GetNumGC() uint32 {
	if m != nil && m.NumGC != nil {
		return *m.NumGC
	}
	return 0
}

func (m *RuntimeSample) GetNumGoRoutines() uint32 {
	if m != nil && m.NumGoRoutines != nil {
		return *m.NumGoRoutines
	}
	return 0
}

func (m *RuntimeSample) GetUptime() int64 {
	if m != nil && m.Uptime != nil {
		return *m.Uptime
	}
	return 0
}

func init() {
}
