// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/platform/proto/jsonschema/jsonschema.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_kernel_platform_jsonschema is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/platform/proto/jsonschema/jsonschema.proto

It has these top-level messages:
	Request
	Response
*/
package com_HailoOSS_kernel_platform_jsonschema

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Request struct {
	Endpoint         *string `protobuf:"bytes,1,opt,name=endpoint" json:"endpoint,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetEndpoint() string {
	if m != nil && m.Endpoint != nil {
		return *m.Endpoint
	}
	return ""
}

type Response struct {
	Jsonschema       *string `protobuf:"bytes,1,opt,name=jsonschema" json:"jsonschema,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetJsonschema() string {
	if m != nil && m.Jsonschema != nil {
		return *m.Jsonschema
	}
	return ""
}

func init() {
}
