// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/platform/proto/profilestart/profilestart.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_kernel_platform_profilestart is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/platform/proto/profilestart/profilestart.proto

It has these top-level messages:
	Request
	Response
*/
package com_HailoOSS_kernel_platform_profilestart

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Output int32

const (
	Output_S3   Output = 0
	Output_FILE Output = 1
)

var Output_name = map[int32]string{
	0: "S3",
	1: "FILE",
}
var Output_value = map[string]int32{
	"S3":   0,
	"FILE": 1,
}

func (x Output) Enum() *Output {
	p := new(Output)
	*p = x
	return p
}
func (x Output) String() string {
	return proto.EnumName(Output_name, int32(x))
}
func (x Output) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Output) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Output_value, data, "Output")
	if err != nil {
		return err
	}
	*x = Output(value)
	return nil
}

type ProfileType int32

const (
	ProfileType_CPU    ProfileType = 0
	ProfileType_MEMORY ProfileType = 1
	ProfileType_BLOCK  ProfileType = 2
)

var ProfileType_name = map[int32]string{
	0: "CPU",
	1: "MEMORY",
	2: "BLOCK",
}
var ProfileType_value = map[string]int32{
	"CPU":    0,
	"MEMORY": 1,
	"BLOCK":  2,
}

func (x ProfileType) Enum() *ProfileType {
	p := new(ProfileType)
	*p = x
	return p
}
func (x ProfileType) String() string {
	return proto.EnumName(ProfileType_name, int32(x))
}
func (x ProfileType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *ProfileType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProfileType_value, data, "ProfileType")
	if err != nil {
		return err
	}
	*x = ProfileType(value)
	return nil
}

type Request struct {
	Id               *string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type             *ProfileType `protobuf:"varint,2,opt,name=type,enum=com.HailoOSS.kernel.platform.profilestart.ProfileType" json:"type,omitempty"`
	Output           *Output      `protobuf:"varint,3,opt,name=output,enum=com.HailoOSS.kernel.platform.profilestart.Output" json:"output,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Request) GetType() ProfileType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ProfileType_CPU
}

func (m *Request) GetOutput() Output {
	if m != nil && m.Output != nil {
		return *m.Output
	}
	return Output_S3
}

type Response struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("com.HailoOSS.kernel.platform.profilestart.Output", Output_name, Output_value)
	proto.RegisterEnum("com.HailoOSS.kernel.platform.profilestart.ProfileType", ProfileType_name, ProfileType_value)
}
