// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/platform/proto/profilestop/profilestop.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_kernel_platform_profilestop is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/platform/proto/profilestop/profilestop.proto

It has these top-level messages:
	Request
	Response
*/
package com_HailoOSS_kernel_platform_profilestop

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Request struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

type Response struct {
	Id               *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ProfileOutput    *string `protobuf:"bytes,2,opt,name=profileOutput" json:"profileOutput,omitempty"`
	BinaryOutput     *string `protobuf:"bytes,3,opt,name=binaryOutput" json:"binaryOutput,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Response) GetProfileOutput() string {
	if m != nil && m.ProfileOutput != nil {
		return *m.ProfileOutput
	}
	return ""
}

func (m *Response) GetBinaryOutput() string {
	if m != nil && m.BinaryOutput != nil {
		return *m.BinaryOutput
	}
	return ""
}

func init() {
}
