// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/platform/proto/healthcheck/healthcheck.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_kernel_platform_healthcheck is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/platform/proto/healthcheck/healthcheck.proto

It has these top-level messages:
	HealthCheck
	Request
	Response
*/
package com_HailoOSS_kernel_platform_healthcheck

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type HealthCheck_Priority int32

const (
	HealthCheck_PAGER   HealthCheck_Priority = 1
	HealthCheck_EMAIL   HealthCheck_Priority = 2
	HealthCheck_WARNING HealthCheck_Priority = 3
)

var HealthCheck_Priority_name = map[int32]string{
	1: "PAGER",
	2: "EMAIL",
	3: "WARNING",
}
var HealthCheck_Priority_value = map[string]int32{
	"PAGER":   1,
	"EMAIL":   2,
	"WARNING": 3,
}

func (x HealthCheck_Priority) Enum() *HealthCheck_Priority {
	p := new(HealthCheck_Priority)
	*p = x
	return p
}
func (x HealthCheck_Priority) String() string {
	return proto.EnumName(HealthCheck_Priority_name, int32(x))
}
func (x HealthCheck_Priority) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *HealthCheck_Priority) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HealthCheck_Priority_value, data, "HealthCheck_Priority")
	if err != nil {
		return err
	}
	*x = HealthCheck_Priority(value)
	return nil
}

type HealthCheck struct {
	Timestamp        *int64                  `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	ServiceName      *string                 `protobuf:"bytes,2,req,name=serviceName" json:"serviceName,omitempty"`
	ServiceVersion   *uint64                 `protobuf:"varint,3,req,name=serviceVersion" json:"serviceVersion,omitempty"`
	Hostname         *string                 `protobuf:"bytes,4,req,name=hostname" json:"hostname,omitempty"`
	InstanceId       *string                 `protobuf:"bytes,5,req,name=instanceId" json:"instanceId,omitempty"`
	HealthCheckId    *string                 `protobuf:"bytes,6,req,name=healthCheckId" json:"healthCheckId,omitempty"`
	IsHealthy        *bool                   `protobuf:"varint,7,req,name=isHealthy" json:"isHealthy,omitempty"`
	ErrorDescription *string                 `protobuf:"bytes,8,opt,name=errorDescription" json:"errorDescription,omitempty"`
	Measurements     []*HealthCheck_KeyValue `protobuf:"bytes,9,rep,name=measurements" json:"measurements,omitempty"`
	Priority         *HealthCheck_Priority   `protobuf:"varint,10,opt,name=priority,enum=com.HailoOSS.kernel.platform.healthcheck.HealthCheck_Priority,def=3" json:"priority,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *HealthCheck) Reset()         { *m = HealthCheck{} }
func (m *HealthCheck) String() string { return proto.CompactTextString(m) }
func (*HealthCheck) ProtoMessage()    {}

const Default_HealthCheck_Priority HealthCheck_Priority = HealthCheck_WARNING

func (m *HealthCheck) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *HealthCheck) GetServiceName() string {
	if m != nil && m.ServiceName != nil {
		return *m.ServiceName
	}
	return ""
}

func (m *HealthCheck) GetServiceVersion() uint64 {
	if m != nil && m.ServiceVersion != nil {
		return *m.ServiceVersion
	}
	return 0
}

func (m *HealthCheck) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

func (m *HealthCheck) GetInstanceId() string {
	if m != nil && m.InstanceId != nil {
		return *m.InstanceId
	}
	return ""
}

func (m *HealthCheck) GetHealthCheckId() string {
	if m != nil && m.HealthCheckId != nil {
		return *m.HealthCheckId
	}
	return ""
}

func (m *HealthCheck) GetIsHealthy() bool {
	if m != nil && m.IsHealthy != nil {
		return *m.IsHealthy
	}
	return false
}

func (m *HealthCheck) GetErrorDescription() string {
	if m != nil && m.ErrorDescription != nil {
		return *m.ErrorDescription
	}
	return ""
}

func (m *HealthCheck) GetMeasurements() []*HealthCheck_KeyValue {
	if m != nil {
		return m.Measurements
	}
	return nil
}

func (m *HealthCheck) GetPriority() HealthCheck_Priority {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return Default_HealthCheck_Priority
}

type HealthCheck_KeyValue struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HealthCheck_KeyValue) Reset()         { *m = HealthCheck_KeyValue{} }
func (m *HealthCheck_KeyValue) String() string { return proto.CompactTextString(m) }
func (*HealthCheck_KeyValue) ProtoMessage()    {}

func (m *HealthCheck_KeyValue) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *HealthCheck_KeyValue) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type Request struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

type Response struct {
	Healthchecks     []*HealthCheck `protobuf:"bytes,1,rep,name=healthchecks" json:"healthchecks,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetHealthchecks() []*HealthCheck {
	if m != nil {
		return m.Healthchecks
	}
	return nil
}

func init() {
	proto.RegisterEnum("com.HailoOSS.kernel.platform.healthcheck.HealthCheck_Priority", HealthCheck_Priority_name, HealthCheck_Priority_value)
}
