// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/platform/proto/stats/stats.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_kernel_platform_stats is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/platform/proto/stats/stats.proto

It has these top-level messages:
	EndpointSLA
	EndpointStat
	EndpointStats
	RusageStats
	RuntimeStats
	PlatformStats
	Request
*/
package com_HailoOSS_kernel_platform_stats

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type EndpointSLA struct {
	Mean             *float32 `protobuf:"fixed32,1,req,name=mean" json:"mean,omitempty"`
	Upper95          *float32 `protobuf:"fixed32,2,req,name=upper95" json:"upper95,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *EndpointSLA) Reset()         { *m = EndpointSLA{} }
func (m *EndpointSLA) String() string { return proto.CompactTextString(m) }
func (*EndpointSLA) ProtoMessage()    {}

func (m *EndpointSLA) GetMean() float32 {
	if m != nil && m.Mean != nil {
		return *m.Mean
	}
	return 0
}

func (m *EndpointSLA) GetUpper95() float32 {
	if m != nil && m.Upper95 != nil {
		return *m.Upper95
	}
	return 0
}

type EndpointStat struct {
	Rate1            *float32 `protobuf:"fixed32,1,req,name=rate1" json:"rate1,omitempty"`
	Rate5            *float32 `protobuf:"fixed32,2,req,name=rate5" json:"rate5,omitempty"`
	Rate15           *float32 `protobuf:"fixed32,3,req,name=rate15" json:"rate15,omitempty"`
	Mean             *float32 `protobuf:"fixed32,4,req,name=mean" json:"mean,omitempty"`
	StdDev           *float32 `protobuf:"fixed32,5,req,name=stdDev" json:"stdDev,omitempty"`
	Upper95          *float32 `protobuf:"fixed32,6,req,name=upper95" json:"upper95,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *EndpointStat) Reset()         { *m = EndpointStat{} }
func (m *EndpointStat) String() string { return proto.CompactTextString(m) }
func (*EndpointStat) ProtoMessage()    {}

func (m *EndpointStat) GetRate1() float32 {
	if m != nil && m.Rate1 != nil {
		return *m.Rate1
	}
	return 0
}

func (m *EndpointStat) GetRate5() float32 {
	if m != nil && m.Rate5 != nil {
		return *m.Rate5
	}
	return 0
}

func (m *EndpointStat) GetRate15() float32 {
	if m != nil && m.Rate15 != nil {
		return *m.Rate15
	}
	return 0
}

func (m *EndpointStat) GetMean() float32 {
	if m != nil && m.Mean != nil {
		return *m.Mean
	}
	return 0
}

func (m *EndpointStat) GetStdDev() float32 {
	if m != nil && m.StdDev != nil {
		return *m.StdDev
	}
	return 0
}

func (m *EndpointStat) GetUpper95() float32 {
	if m != nil && m.Upper95 != nil {
		return *m.Upper95
	}
	return 0
}

type EndpointStats struct {
	EndpointName     *string       `protobuf:"bytes,1,req,name=endpointName" json:"endpointName,omitempty"`
	Sla              *EndpointSLA  `protobuf:"bytes,2,req,name=sla" json:"sla,omitempty"`
	Success          *EndpointStat `protobuf:"bytes,3,req,name=success" json:"success,omitempty"`
	Error            *EndpointStat `protobuf:"bytes,4,req,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *EndpointStats) Reset()         { *m = EndpointStats{} }
func (m *EndpointStats) String() string { return proto.CompactTextString(m) }
func (*EndpointStats) ProtoMessage()    {}

func (m *EndpointStats) GetEndpointName() string {
	if m != nil && m.EndpointName != nil {
		return *m.EndpointName
	}
	return ""
}

func (m *EndpointStats) GetSla() *EndpointSLA {
	if m != nil {
		return m.Sla
	}
	return nil
}

func (m *EndpointStats) GetSuccess() *EndpointStat {
	if m != nil {
		return m.Success
	}
	return nil
}

func (m *EndpointStats) GetError() *EndpointStat {
	if m != nil {
		return m.Error
	}
	return nil
}

type RusageStats struct {
	UserTime         *float32 `protobuf:"fixed32,1,req,name=userTime" json:"userTime,omitempty"`
	SystemTime       *float32 `protobuf:"fixed32,2,req,name=systemTime" json:"systemTime,omitempty"`
	MaxRss           *int64   `protobuf:"varint,3,req,name=maxRss" json:"maxRss,omitempty"`
	InBlock          *int64   `protobuf:"varint,4,req,name=inBlock" json:"inBlock,omitempty"`
	OuBlock          *int64   `protobuf:"varint,5,req,name=ouBlock" json:"ouBlock,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RusageStats) Reset()         { *m = RusageStats{} }
func (m *RusageStats) String() string { return proto.CompactTextString(m) }
func (*RusageStats) ProtoMessage()    {}

func (m *RusageStats) GetUserTime() float32 {
	if m != nil && m.UserTime != nil {
		return *m.UserTime
	}
	return 0
}

func (m *RusageStats) GetSystemTime() float32 {
	if m != nil && m.SystemTime != nil {
		return *m.SystemTime
	}
	return 0
}

func (m *RusageStats) GetMaxRss() int64 {
	if m != nil && m.MaxRss != nil {
		return *m.MaxRss
	}
	return 0
}

func (m *RusageStats) GetInBlock() int64 {
	if m != nil && m.InBlock != nil {
		return *m.InBlock
	}
	return 0
}

func (m *RusageStats) GetOuBlock() int64 {
	if m != nil && m.OuBlock != nil {
		return *m.OuBlock
	}
	return 0
}

type RuntimeStats struct {
	HeapInUse        *uint64 `protobuf:"varint,1,req,name=heapInUse" json:"heapInUse,omitempty"`
	HeapTotal        *uint64 `protobuf:"varint,2,req,name=heapTotal" json:"heapTotal,omitempty"`
	HeapReleased     *uint64 `protobuf:"varint,3,req,name=heapReleased" json:"heapReleased,omitempty"`
	LastGCDuration   *uint64 `protobuf:"varint,4,req,name=lastGCDuration" json:"lastGCDuration,omitempty"`
	NumGC            *uint32 `protobuf:"varint,5,req,name=numGC" json:"numGC,omitempty"`
	NumGoRoutines    *uint32 `protobuf:"varint,6,req,name=numGoRoutines" json:"numGoRoutines,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RuntimeStats) Reset()         { *m = RuntimeStats{} }
func (m *RuntimeStats) String() string { return proto.CompactTextString(m) }
func (*RuntimeStats) ProtoMessage()    {}

func (m *RuntimeStats) GetHeapInUse() uint64 {
	if m != nil && m.HeapInUse != nil {
		return *m.HeapInUse
	}
	return 0
}

func (m *RuntimeStats) GetHeapTotal() uint64 {
	if m != nil && m.HeapTotal != nil {
		return *m.HeapTotal
	}
	return 0
}

func (m *RuntimeStats) GetHeapReleased() uint64 {
	if m != nil && m.HeapReleased != nil {
		return *m.HeapReleased
	}
	return 0
}

func (m *RuntimeStats) GetLastGCDuration() uint64 {
	if m != nil && m.LastGCDuration != nil {
		return *m.LastGCDuration
	}
	return 0
}

func (m *RuntimeStats) GetNumGC() uint32 {
	if m != nil && m.NumGC != nil {
		return *m.NumGC
	}
	return 0
}

func (m *RuntimeStats) GetNumGoRoutines() uint32 {
	if m != nil && m.NumGoRoutines != nil {
		return *m.NumGoRoutines
	}
	return 0
}

type PlatformStats struct {
	ServiceName      *string          `protobuf:"bytes,1,req,name=serviceName" json:"serviceName,omitempty"`
	ServiceVersion   *uint64          `protobuf:"varint,2,req,name=serviceVersion" json:"serviceVersion,omitempty"`
	Hostname         *string          `protobuf:"bytes,3,req,name=hostname" json:"hostname,omitempty"`
	InstanceId       *string          `protobuf:"bytes,4,req,name=instanceId" json:"instanceId,omitempty"`
	Status           *string          `protobuf:"bytes,5,req,name=status" json:"status,omitempty"`
	Timestamp        *int64           `protobuf:"varint,6,req,name=timestamp" json:"timestamp,omitempty"`
	Uptime           *int64           `protobuf:"varint,7,req,name=uptime" json:"uptime,omitempty"`
	Rusage           *RusageStats     `protobuf:"bytes,8,req,name=rusage" json:"rusage,omitempty"`
	Runtime          *RuntimeStats    `protobuf:"bytes,9,req,name=runtime" json:"runtime,omitempty"`
	Endpoints        []*EndpointStats `protobuf:"bytes,10,rep,name=endpoints" json:"endpoints,omitempty"`
	ServiceType      *string          `protobuf:"bytes,11,opt,name=serviceType" json:"serviceType,omitempty"`
	AzName           *string          `protobuf:"bytes,12,opt,name=azName" json:"azName,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PlatformStats) Reset()         { *m = PlatformStats{} }
func (m *PlatformStats) String() string { return proto.CompactTextString(m) }
func (*PlatformStats) ProtoMessage()    {}

func (m *PlatformStats) GetServiceName() string {
	if m != nil && m.ServiceName != nil {
		return *m.ServiceName
	}
	return ""
}

func (m *PlatformStats) GetServiceVersion() uint64 {
	if m != nil && m.ServiceVersion != nil {
		return *m.ServiceVersion
	}
	return 0
}

func (m *PlatformStats) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

func (m *PlatformStats) GetInstanceId() string {
	if m != nil && m.InstanceId != nil {
		return *m.InstanceId
	}
	return ""
}

func (m *PlatformStats) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *PlatformStats) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *PlatformStats) GetUptime() int64 {
	if m != nil && m.Uptime != nil {
		return *m.Uptime
	}
	return 0
}

func (m *PlatformStats) GetRusage() *RusageStats {
	if m != nil {
		return m.Rusage
	}
	return nil
}

func (m *PlatformStats) GetRuntime() *RuntimeStats {
	if m != nil {
		return m.Runtime
	}
	return nil
}

func (m *PlatformStats) GetEndpoints() []*EndpointStats {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *PlatformStats) GetServiceType() string {
	if m != nil && m.ServiceType != nil {
		return *m.ServiceType
	}
	return ""
}

func (m *PlatformStats) GetAzName() string {
	if m != nil && m.AzName != nil {
		return *m.AzName
	}
	return ""
}

type Request struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func init() {
}
